/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_yunlongzhang_opencvtest_Helper_OpenCVHelper */

#ifndef _Included_com_example_yunlongzhang_opencvtest_Helper_OpenCVHelper
#define _Included_com_example_yunlongzhang_opencvtest_Helper_OpenCVHelper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_yunlongzhang_opencvtest_Helper_OpenCVHelper
 * Method:    gray
 * Signature: (III)[I
 */
JNIEXPORT jintArray JNICALL Java_com_example_yunlongzhang_opencvtest_Helper_OpenCVHelper_gray
  (JNIEnv *, jclass, jintArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
